# Form implementation generated from reading ui file 'gui\Disclaimer.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DisclaimerDialog(object):
    def setupUi(self, DisclaimerDialog):
        DisclaimerDialog.setObjectName("DisclaimerDialog")
        DisclaimerDialog.resize(369, 331)
        DisclaimerDialog.setSizeGripEnabled(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DisclaimerDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(DisclaimerDialog)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.widget)

        self.retranslateUi(DisclaimerDialog)
        self.buttonBox.accepted.connect(DisclaimerDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DisclaimerDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DisclaimerDialog)

    def retranslateUi(self, DisclaimerDialog):
        _translate = QtCore.QCoreApplication.translate
        DisclaimerDialog.setWindowTitle(_translate("DisclaimerDialog", "WARNING - Disclaimer"))
        self.label.setText(_translate("DisclaimerDialog", "<html><head/><body><p><span style=\" font-weight:700;\">WARNING:</span> It is the user\'s responsibility to be aware of any rules, policies, laws, or regulations that govern use of this function. Attaching an image of someone else\'s signature or reusing a document signed by someone else may be a violation of policy, law, or regulation. Any use of this function is AT THE USER\'S OWN RISK. The creator of this program assumes no liability whatsoever arising from the use of this function or any other function provided in this program.</p></body></html>"))
        self.checkBox.setText(_translate("DisclaimerDialog", "I understand the above and I agree"))
